import useSound from 'use-sound';

// Extremely short base64 encoded 'tick' and 'pop' sounds for UI feedback
const tickSound = 'data:audio/mp3;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjYxLjEuMTAwAAAAAAAAAAAAAAD/+0DAAAAAAAAAAAAAAAAAAAAAAABJbmZvAAAADQAAAAEAAAA2AAB1dQAOEBIVFhkdICIjJSgpLTAyNDY5Oz5AQUJER0lLTE5SU1ZYWlxfYmRnaGxvcXN1eHt+f4KFiIuOkZOWmZudn6Kkp6qtr7K1t7q8v8LExsjLztHT1tja3N/h5OXo6+zt8PP2+Pv+////AAAADExhdmM2MS4zAAAAAAAAAAAAAAAAJAXAAAAAAAAANgAAAAAAAAD/+0DAAAAAAE2AAAJAAAO2h04AAAAAACAAcKAgICAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgP/7AMAAAAAFQAACQAA//7AMAAAAAFQAACQAA';
const popSound = 'data:audio/mp3;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjYxLjEuMTAwAAAAAAAAAAAAAAD/+0DAAAAAAAAAAAAAAAAAAAAAAABJbmZvAAAADQAAAAEAAAA2AAB1dQAOEBIVFhkdICIjJSgpLTAyNDY5Oz5AQUJER0lLTE5SU1ZYWlxfYmRnaGxvcXN1eHt+f4KFiIuOkZOWmZudn6Kkp6qtr7K1t7q8v8LExsjLztHT1tja3N/h5OXo6+zt8PP2+Pv+////AAAADExhdmM2MS4zAAAAAAAAAAAAAAAAJAXAAAAAAAAANgAAAAAAAAD/+0DAAAAAAE2AAAJAAAO2h04AAAAAACAAcKAgICAAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgP/7AMAAAAAFQAACQAA//7AMAAAAAFQAACQAA';

export function useSoundEffects() {
  const [playHover] = useSound(tickSound, { volume: 0.1 });
  const [playClick] = useSound(popSound, { volume: 0.2 });

  return { playHover, playClick };
}
